---
title: "Data Munging"
output: html_document
---


```{r}
setwd("~/Desktop/CollegeScorecard_Raw_Data")
data1996 <- read.csv((file.path="MERGED1996_PP.csv"), header=TRUE, na.strings="NULL", sep=",")
data1997 <- read.csv((file.path="MERGED1997_PP.csv"), header=TRUE, na.strings="NULL", sep=",")
data1998 <- read.csv((file.path="MERGED1998_PP.csv"), header=TRUE, na.strings="NULL", sep=",")
data1999 <- read.csv((file.path="MERGED1999_PP.csv"), header=TRUE, na.strings="NULL", sep=",")
data2000 <- read.csv((file.path="MERGED2000_PP.csv"), header=TRUE, na.strings="NULL", sep=",")
data2001 <- read.csv((file.path="MERGED2001_PP.csv"), header=TRUE, na.strings="NULL", sep=",")
data2002 <- read.csv((file.path="MERGED2002_PP.csv"), header=TRUE, na.strings="NULL", sep=",")
data2003 <- read.csv((file.path="MERGED2003_PP.csv"), header=TRUE, na.strings="NULL", sep=",")
data2004 <- read.csv((file.path="MERGED2004_PP.csv"), header=TRUE, na.strings="NULL", sep=",")
data2005 <- read.csv((file.path="MERGED2005_PP.csv"), header=TRUE, na.strings="NULL", sep=",")
data2006 <- read.csv((file.path="MERGED2006_PP.csv"), header=TRUE, na.strings="NULL", sep=",")
data2007 <- read.csv((file.path="MERGED2007_PP.csv"), header=TRUE, na.strings="NULL", sep=",")
data2008 <- read.csv((file.path="MERGED2008_PP.csv"), header=TRUE, na.strings="NULL", sep=",")
data2009 <- read.csv((file.path="MERGED2009_PP.csv"), header=TRUE, na.strings="NULL", sep=",")
data2010 <- read.csv((file.path="MERGED2010_PP.csv"), header=TRUE, na.strings="NULL", sep=",")
data2011 <- read.csv((file.path="MERGED2011_PP.csv"), header=TRUE, na.strings="NULL", sep=",")
data2012 <- read.csv((file.path="MERGED2012_PP.csv"), header=TRUE, na.strings="NULL", sep=",")
data2013 <- read.csv((file.path="MERGED2013_PP.csv"), header=TRUE, na.strings="NULL", sep=",")
data.frame <- list('data1996','data1997','data1998','data1999','data2000','data2001','data2002','data2003','data2004','data2005','data2006','data2007','data2008','data2009','data2010','data2011','data2012','data2013')

years = 1996:2013

  allyears <- data.frame()
  for (i in 1:length(data.frame)){
    allyears <- rbind(allyears, cbind(eval(parse(text = data.frame[[i]])), rep(years[i], nrow(eval(parse(text = data.frame[[i]]))))))
  }
  
  str(allyears)
```

```{r}
#Coerce columns to ints
  
true_numerics = c("RPY_3YR_RT",
"COMPL_RPY_3YR_RT",
"NONCOM_RPY_3YR_RT",
"LO_INC_RPY_3YR_RT",
"MD_INC_RPY_3YR_RT",
"HI_INC_RPY_3YR_RT",
"DEP_RPY_3YR_RT",
"IND_RPY_3YR_RT",
"PELL_RPY_3YR_RT",
"NOPELL_RPY_3YR_RT",
"FEMALE_RPY_3YR_RT",
"MALE_RPY_3YR_RT",
"FIRSTGEN_RPY_3YR_RT",
"NOTFIRSTGEN_RPY_3YR_RT",
"RPY_5YR_RT",
"COMPL_RPY_5YR_RT",
"NONCOM_RPY_5YR_RT",
"LO_INC_RPY_5YR_RT",
"MD_INC_RPY_5YR_RT",
"HI_INC_RPY_5YR_RT",
"DEP_RPY_5YR_RT",
"IND_RPY_5YR_RT",
"PELL_RPY_5YR_RT",
"NOPELL_RPY_5YR_RT",
"FEMALE_RPY_5YR_RT",
"MALE_RPY_5YR_RT",
"FIRSTGEN_RPY_5YR_RT",
"NOTFIRSTGEN_RPY_5YR_RT",
"RPY_7YR_RT",
"COMPL_RPY_7YR_RT",
"NONCOM_RPY_7YR_RT",
"LO_INC_RPY_7YR_RT",
"MD_INC_RPY_7YR_RT",
"HI_INC_RPY_7YR_RT",
"DEP_RPY_7YR_RT",
"IND_RPY_7YR_RT",
"PELL_RPY_7YR_RT",
"NOPELL_RPY_7YR_RT",
"FEMALE_RPY_7YR_RT",
"MALE_RPY_7YR_RT",
"FIRSTGEN_RPY_7YR_RT",
"NOTFIRSTGEN_RPY_7YR_RT",
"INC_PCT_LO",
"DEP_STAT_PCT_IND",
"DEP_INC_PCT_LO",
"IND_INC_PCT_LO",
"PAR_ED_PCT_1STGEN",
"INC_PCT_M1",
"INC_PCT_M2",
"INC_PCT_H1",
"INC_PCT_H2",
"DEP_INC_PCT_M1",
"DEP_INC_PCT_M2",
"DEP_INC_PCT_H1",
"DEP_INC_PCT_H2",
"IND_INC_PCT_M1",
"IND_INC_PCT_M2",
"IND_INC_PCT_H1",
"IND_INC_PCT_H2",
"PAR_ED_PCT_MS",
"PAR_ED_PCT_HS",
"PAR_ED_PCT_PS",
"APPL_SCH_PCT_GE2",
"APPL_SCH_PCT_GE3",
"APPL_SCH_PCT_GE4",
"APPL_SCH_PCT_GE5",
"DEP_INC_AVG",
"IND_INC_AVG",
"DEBT_MDN",
"GRAD_DEBT_MDN",
"WDRAW_DEBT_MDN",
"LO_INC_DEBT_MDN",
"MD_INC_DEBT_MDN",
"HI_INC_DEBT_MDN",
"DEP_DEBT_MDN",
"IND_DEBT_MDN",
"PELL_DEBT_MDN",
"NOPELL_DEBT_MDN",
"FEMALE_DEBT_MDN",
"MALE_DEBT_MDN",
"FIRSTGEN_DEBT_MDN",
"NOTFIRSTGEN_DEBT_MDN",
"DEBT_N",
"GRAD_DEBT_N",
"WDRAW_DEBT_N",
"LO_INC_DEBT_N",
"MD_INC_DEBT_N",
"HI_INC_DEBT_N",
"DEP_DEBT_N",
"IND_DEBT_N",
"PELL_DEBT_N",
"NOPELL_DEBT_N",
"FEMALE_DEBT_N",
"MALE_DEBT_N",
"FIRSTGEN_DEBT_N",
"NOTFIRSTGEN_DEBT_N",
"GRAD_DEBT_MDN10YR",
"CUML_DEBT_N",
"CUML_DEBT_P90",
"CUML_DEBT_P75",
"CUML_DEBT_P25",
"CUML_DEBT_P10",
"INC_N",
"DEP_INC_N",
"IND_INC_N",
"DEP_STAT_N",
"PAR_ED_N",
"APPL_SCH_N",
"DEBT_MDN_SUPP",
"GRAD_DEBT_MDN_SUPP",
"GRAD_DEBT_MDN10YR_SUPP",
"RPY_3YR_RT_SUPP",
"LO_INC_RPY_3YR_RT_SUPP",
"MD_INC_RPY_3YR_RT_SUPP",
"HI_INC_RPY_3YR_RT_SUPP",
"COMPL_RPY_3YR_RT_SUPP",
"NONCOM_RPY_3YR_RT_SUPP",
"DEP_RPY_3YR_RT_SUPP",
"IND_RPY_3YR_RT_SUPP",
"PELL_RPY_3YR_RT_SUPP",
"NOPELL_RPY_3YR_RT_SUPP",
"FEMALE_RPY_3YR_RT_SUPP",
"MALE_RPY_3YR_RT_SUPP",
"FIRSTGEN_RPY_3YR_RT_SUPP",
"NOTFIRSTGEN_RPY_3YR_RT_SUPP",
"C150_L4_POOLED_SUPP",
"C150_4_POOLED_SUPP",
"C200_L4_POOLED_SUPP")

true_ints = c("UNITID",
"OPEID",
"opeid6",
"SATVR25",
"SATVR75",
"SATMT75",
"SATWR25",
"SATWR75",
"SATVRMID",
"SATMTMID",
"SATWRMID",
"ACTCM25",
"ACTCM75",
"ACTEN25",
"ACTEN75",
"ACTMT25",
"ACTMT75",
"ACTWR25",
"ACTWR75",
"ACTCMMID",
"ACTENMID",
"ACTMTMID",
"ACTWRMID",
"SAT_AVG",
"SAT_AVG_ALL",
"UGDS",
"COSTT4_A",
"COSTT4_P",
"TUITIONFEE_IN",
"TUITIONFEE_OUT",
"TUITIONFEE_PROG",
"TUITFTE",
"INEXPFTE",
"AVGFACSAL",
"poolyrs",
"D150_4",
"D150_L4",
"D150_4_POOLED",
"D150_L4_POOLED",
"D200_4",
"D200_L4",
"poolyrs200",
"D200_4_POOLED",
"D200_L4_POOLED")
  
for (i in 1:ncol(allyears)){
  
  if (class(allyears[, i]) == 'integer'){
    allyears[ ,i] = as.factor(allyears[, i])
  }
  
}
allyears[true_numerics] = apply(allyears[true_numerics], 2, as.numeric)
allyears[true_ints] = apply(allyears[true_ints], 2, as.integer)

```

