---
title: "CollegeScorecard"
output: html_document
---

```{r}
require("doBy")
source("funcs.R")
library("tidyr")
#make a symlink from the data dir in the directory where this file is to the desired data file
datafile <- "data/merged.csv"
```


```{r, cache=TRUE}
college.df <- read.csv(datafile, header = TRUE, na.strings = c("NULL", "PrivacySuppressed"))
```

What is the ratio of NAs to non-NAs overall? (Note that NA includes both "Null" and "PrivacySuppressed".)
```{r}
sum(is.na(college.df))/sum(!is.na(college.df))
```

Yes, that's greater than 1 - there are more NAs than non NAs in this dataset. Which column has the most NAs, and how many are there?

```{r}
col.na.ratios <- colSums(is.na(college.df))/colSums(!is.na(college.df))
col.max.na <- c(max(col.na.ratios), nrow(college.df), which.max(col.na.ratios))
names(col.max.na) <- c("number of NAs", "number of rows", "column name")

col.max.na
```

And the fewest NAs?

```{r}
col.na.ratios <- colSums(is.na(college.df))/colSums(!is.na(college.df))
col.min.na <- c(min(col.na.ratios), nrow(college.df), which.min(col.na.ratios))
names(col.min.na) <- c("number of NAs", "number of rows", "column name")

col.min.na
```


```{r}
head(
  summaryBy(
    FEMALE_COMP_ORIG_YR4_RT + FEMALE_COMP_ORIG_YR3_RT + FEMALE_COMP_ORIG_YR2_RT + FEMALE_COMP_ORIG_YR6_RT + FEMALE_COMP_ORIG_YR8_RT ~ region + PREDDEG, 
    data=college.df,
    FUN=function(x) {c(m =mean(x, na.rm = TRUE),s =sd(x, na.rm = TRUE)) }
    )
)
```

```{r}
names(college.df) <- rename_by_yaml(college.df,"data/data_dictionary.yaml")
kvs <- gather(college.df)
```
